version: "3.8"

services:

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://192.168.4.8:3128
        - HTTPS_PROXY=http://192.168.4.8:3128
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./api
      args:
        - MAVEN_OPTS=-DproxySet=true -DproxyHost=192.168.4.8 -DproxyPort=3128
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
