version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - web-app
    container_name: nginx-proxy
    dns:
      - IP_DNS
      - webcube.pfe.dns
      
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://192.168.4.8:3128
        - HTTPS_PROXY=http://192.168.4.8:3128
    ports:
      - "3000:3000"
    depends_on:
      - api
    container_name: web-app
    dns:
      - IP_DNS
      - webcube.pfe.dns

  api:
    build:
      context: ./api
      args:
        - MAVEN_OPTS=-DproxySet=true -DproxyHost=192.168.4.8 -DproxyPort=3128
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    container_name: api
    dns:
      - IP_DNS
      - webcube.pfe.dns
    volumes:
      - /code:/api/code
    
