Vagrant.configure("2") do |config|
  config.vm.define "VM-jobe" do |machine|
    machine.vm.hostname = "VM-jobe"
    machine.vm.box = "debian/bullseye64"
    machine.vm.network "private_network", ip: "192.168.56.10"

    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "VM-jobe"]
      v.customize ["modifyvm", :id, "--groups", "/S9-PFE"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--memory", 2*1024]
    end
    
    machine.vm.provision "shell", path: "setup-coderunner.sh"
  end
end