name: vagrant

on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
      up:
        required: true
        type: boolean
        default: false
      destroy:
        required: true
        type: boolean
        default: false

jobs:
  vagrant:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component-name:
          - vagrant
    environment:
      name: ${{ inputs.env-name }}
    steps:
      # pull the source code
      - uses: actions/checkout@v3

      # execute vagrant up and destroy on remote VM-jobe server
      - name: Run SSH and Execute Commands
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem etudis@$SSH_IP <<EOF
            cd /home/etudis/Documents/WebCube/VM-jobe
            if [ "${{ inputs.up }}" = "true" ] && [ "${{ inputs.down }}" = "false" ]; then
              vagrant up
            fi
            if [ "${{ inputs.up }}" = "false" ] && [ "${{ inputs.down }}" = "true" ]; then
              vagrant destroy -f
            fi
          EOF
